_extends: .github
tag-template: ctrlplane-plugin-$NEXT_MINOR_VERSION
template: |
  ## What's Changed

  $CHANGES

categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'maintenance'
      - 'documentation'

change-template: '* $TITLE (#$NUMBER) @$AUTHOR'
